id: IB845E54D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T02:23:24+00:00'
last_modified: '2022-06-08T12:20:57.729079+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23183
  title: གཏེར་ཆོས། དཔའ་བོ་ཆོས་དབྱིངས་རྡོ་རྗེ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    16EA:
      image_group_id: I0389
      title: ''
      total_pages: 646
      order: 1
      base_file: 16EA.txt
    002D:
      image_group_id: I0390
      title: ''
      total_pages: 625
      order: 2
      base_file: 002D.txt
    3A16:
      image_group_id: I0391
      title: ''
      total_pages: 631
      order: 3
      base_file: 3A16.txt
    AA83:
      image_group_id: I0392
      title: ''
      total_pages: 629
      order: 4
      base_file: AA83.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
