id: IB845E54D
legacy_id: P009624
ocr_import_info:
  bdrc_scan_id: W23183
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T02:19:23'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T00:58:20.548649+00:00'
last_modified: 2022-09-02 08:59:06.465744
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23183
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23183
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཏེར་ཆོས། དཔའ་བོ་ཆོས་དབྱིངས་རྡོ་རྗེ།
  author: ཨ་པཾ་གཏེར་སྟོན་དཔའ་བོ་ཆོས་དབྱིངས་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.7964242970440325
  ocr_word_median_confidence_index: 0.8899999856948853
quality: null
bases:
  I0391:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0391
      total_pages: 631
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I0391.txt
    statistics:
      ocr_word_median_confidence_index: 0.8799999952316284
      ocr_word_mean_confidence_index: 0.7881296736454986
    legacy_id: v003
  I0390:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0390
      total_pages: 625
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I0390.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.7986206686627227
    legacy_id: v002
  I0389:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0389
      total_pages: 646
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I0389.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.8024356082464275
    legacy_id: v001
  I0392:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0392
      total_pages: 629
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I0392.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.7962522152086622
    legacy_id: v004
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
